site_name: Wordle Bot
theme:
  name: material
  palette:
    scheme: slate

plugins:
  - search
  - mkdocstrings:
      default_handler: python

nav:
  - Home: index.md
  - Today's Wordle: final_table.md
  - Documentation: docs.md