name: documentation

on:
  push:
    branches:
      - main
  schedule:
    - cron: "30 0 * * *"

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Play Wordle
        run: |
          python main.py --export
      - name: Sphinx build
        run: |
          sphinx-apidoc -f -o docs/source $GITHUB_WORKSPACE/wordle_bot
          sphinx-build docs/source docs/build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build
          force_orphan: true
